# for now, only accidents-prediction is supported, later we can add Żabka, airbnb or any other
downstream_task: 'accidents-prediction'
params:
  ORGANIZED_DATASETS_LOCATION: "/path/to/gradient/data/organized-datasets"

