#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

required_prefix="GRA-[0-9]+"

commit_message=$(cat $COMMIT_MSG_FILE)

# Check if the commit msg starts with the required prefix
if [[ ! "$commit_message" =~ ^$required_prefix ]]; then
  echo "Error: Commit message must start with '$required_prefix [message]'."
  echo "For example: 'GRA-6489 Rename variables'"
  exit 1
fi